spring:
  main:
    banner-mode: off
  datasource:
    url: "jdbc:mysql://localhost:3306/my_db?useSSL=false&serverTimezone=UTC"
    username: admin
    password: mypas
  profiles:
    active: default

server:
  port: 8080
  servlet:
    context-path: /rest-jpa
